export interface BocTrip {
    id: number,
    tripDate: string,
    requisitionerPurpose: string,
    currentMeterReading: number,
    eLogId: number,
    driverId: number,
    vehicleId: number,
    createdAt: string,
    updatedAt: string,
    vehicle: {
        id: number,
        vehicleNumber: number,
        model: string,
        isServiceable: boolean,
        vehicleType: string,
        subUnitId: number,
        vehiclesPlatformsId: number,
        createdAt: string,
        updatedAt: string
    },
    driver: {
        id: number,
        name: string,
        email: string,
        username: string,
        password: string,
        hasBaseLevelVehiclesAccess: boolean,
        provider: string,
        subUnitId: number,
        adminSubUnitId: number,
        serviceId: number,
        commandId: number,
        baseAdminId: number,
        createdAt: string,
        updatedAt: string
    },
    eLog: {
        id: number,
        startTime: string,
        endTime: string,
        stationaryRunningTime: number,
        meterReading: number,
        totalDistance: number,
        fuelReceived: number,
        fuelType: string,
        remarks: string,
        POSONumber: number,
        requisitionerPurpose: string,
        destinationId: number,
        createdAt: string,
        updatedAt: string,
        destination: object
    }
}
