export interface MtracForm {
    id: number,
    overAllRisk: string,
    dispatchDate: string,
    dispatchTime: string,
    releaseDate: string,
    releaseTime: string,
    isAdditionalDetailApplicable: boolean,
    driverRiskAssessmentChecklist: string[],
    otherRiskAssessmentChecklist: string[],
    safetyMeasures: string,
    rankAndName: string,
    personalPin: string,
    filledBy: string,
    status: string,
    tripId: number,
    createdAt: string,
    updatedAt: string,
    quizzes: string[],
    trip: {
        id: number,
        tripDate: string,
        approvalStatus: string,
        currentMeterReading: number,
        tripStatus: string,
        endedAt: string,
        aviDate: string,
        driverId: number,
        vehiclesId: number,
        approvingOfficerId: number,
        createdAt: string,
        updatedAt: string,
        vehicle: {
            id: number,
            vehicleNumber: number,
            model: number,
            isServiceable: boolean,
            vehicleType: string,
            subUnitId: number,
            vehiclesPlatformsId: number,
            createdAt: string,
            updatedAt: string,
            subUnit: {
                id: number,
                name: string,
                description: number,
                baseId: number,
                createdAt: string,
                updatedAt: string,
                base: {
                    id: number,
                    name: string,
                    description: number,
                    commandId: number,
                    createdAt: string,
                    updatedAt: string,
                    command: {
                        id: number,
                        name: string,
                        description: number,
                        createdAt: string,
                        updatedAt: string,
                        serviceId: number,
                        service: {
                            id: number,
                            name: string,
                            description: string,
                            createdAt: string,
                            updatedAt: string
                        }
                    }
                }
            }
        },
        approvingOfficer: {
            id: number,
            name: string,
            email: string,
            username: string,
            password: string,
            hasBaseLevelVehiclesAccess: boolean,
            provider: string,
            subUnitId: number,
            adminSubUnitId: number,
            serviceId: number,
            commandId: number,
            baseAdminId: number,
            createdAt: string,
            updatedAt: string
        },
        driver: {
            id: number,
            name: string,
            email: string,
            username: string,
            password: string,
            hasBaseLevelVehiclesAccess: boolean,
            provider: string,
            subUnitId: number,
            adminSubUnitId: number,
            serviceId: number,
            commandId: number,
            baseAdminId: number,
            createdAt: string,
            updatedAt: string
        }
    }
}
