// @ts-nocheck
import { UserRoles as Role } from "../../../core/types/db-enum";
import {AccessTypes, SettingsModules} from "../enums";

export const settingsAccessControl = {
  [SettingsModules.AuditLog]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
  },
  [SettingsModules.User]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
  },
  [SettingsModules.Vehicle]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
  },
  [SettingsModules.Service]: {
    [AccessTypes.CREATE]: [Role.SUPER_ADMIN],
    [AccessTypes.READ]: [Role.SUPER_ADMIN],
    [AccessTypes.UPDATE]: [Role.SUPER_ADMIN],
    [AccessTypes.DELETE]: [Role.SUPER_ADMIN],
  },
  [SettingsModules.ServiceAdmin]: {
    [AccessTypes.CREATE]: [Role.SUPER_ADMIN],
    [AccessTypes.READ]: [Role.SUPER_ADMIN],
    [AccessTypes.UPDATE]: [Role.SUPER_ADMIN],
    [AccessTypes.DELETE]: [Role.SUPER_ADMIN],
  },
  [SettingsModules.Command]: {
    [AccessTypes.CREATE]: [Role.SUPER_ADMIN, Role.SERVICES],
    [AccessTypes.READ]: [Role.SUPER_ADMIN, Role.SERVICES],
    [AccessTypes.UPDATE]: [Role.SUPER_ADMIN, Role.SERVICES],
    [AccessTypes.DELETE]: [Role.SUPER_ADMIN, Role.SERVICES],
  },
  [SettingsModules.CommandAdmin]: {
    [AccessTypes.CREATE]: [Role.SUPER_ADMIN, Role.SERVICES],
    [AccessTypes.READ]: [Role.SUPER_ADMIN, Role.SERVICES],
    [AccessTypes.UPDATE]: [Role.SUPER_ADMIN, Role.SERVICES],
    [AccessTypes.DELETE]: [Role.SUPER_ADMIN, Role.SERVICES],
  },
  [SettingsModules.Base]: {
    [AccessTypes.CREATE]: [Role.SUPER_ADMIN, Role.SERVICES, Role.COMMAND],
    [AccessTypes.READ]: [Role.SUPER_ADMIN, Role.SERVICES, Role.COMMAND],
    [AccessTypes.UPDATE]: [Role.SUPER_ADMIN, Role.SERVICES, Role.COMMAND],
    [AccessTypes.DELETE]: [Role.SUPER_ADMIN, Role.SERVICES, Role.COMMAND],
  },
  [SettingsModules.BaseAdmin]: {
    [AccessTypes.CREATE]: [Role.SUPER_ADMIN, Role.SERVICES, Role.COMMAND],
    [AccessTypes.READ]: [Role.SUPER_ADMIN, Role.SERVICES, Role.COMMAND],
    [AccessTypes.UPDATE]: [Role.SUPER_ADMIN, Role.SERVICES, Role.COMMAND],
    [AccessTypes.DELETE]: [Role.SUPER_ADMIN, Role.SERVICES, Role.COMMAND],
  },
  [SettingsModules.AuditorAdmin]: {
    [AccessTypes.CREATE]: [Role.SUPER_ADMIN],
    [AccessTypes.READ]: [Role.SUPER_ADMIN],
    [AccessTypes.UPDATE]: [Role.SUPER_ADMIN],
    [AccessTypes.DELETE]: [Role.SUPER_ADMIN],
  },
  [SettingsModules.SubUnits]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
  },
  [SettingsModules.SubUnitsAdmin]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
  },
  [SettingsModules.MaintenanceAdmin]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
    ],
  },
  [SettingsModules.LicenseClass]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
  },
  [SettingsModules.VehiclePlatform]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
  },
  [SettingsModules.VehicleType]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
    ],
  },
  [SettingsModules.EditDestination]: {
    [AccessTypes.CREATE]: [],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.DELETE]: [],
  },
  [SettingsModules.MTBroadcast]: {
    [AccessTypes.CREATE]: [Role.BASE],
    [AccessTypes.READ]: [Role.BASE],
    [AccessTypes.UPDATE]: [],
    [AccessTypes.DELETE]: [Role.BASE],
  },
  [SettingsModules.BOS_AOS_POL_DI_AHS]: {
    [AccessTypes.CREATE]: [],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
  },
  [SettingsModules.MTRACForm]: {
    [AccessTypes.CREATE]: [],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.DELETE]: [],
  },
  [SettingsModules.EditDestination]: {
    [AccessTypes.CREATE]: [],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.DELETE]: [],
  },
  [SettingsModules.ElogBook]: {
    [AccessTypes.CREATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.READ]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.UPDATE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
    [AccessTypes.DELETE]: [
      Role.SUPER_ADMIN,
      Role.SERVICES,
      Role.COMMAND,
      Role.BASE,
      Role.SUB_UNIT,
    ],
  },
};
