name: ci-cd for MTFleet-Web # This specifies the name of the workflow
on:
  push:
    branches:
      - "master" # This specifies the branch to trigger the workflow on

jobs:
  run-script:
    runs-on: self-hosted  # This specifies to run on a self-hosted runner
    steps:
      - uses: actions/checkout@v2  # Checks out your repository code
      - name: Run continuous deployment script
        run: |  # This defines the command to run
          bash /home/azureuser/web_deploy.sh