name: Self-Hosted-Runner Keep-Alive for MTFleet-Web

on:
  schedule:
    - cron: "0 0 * * *" 

jobs:
  run-script:
    runs-on: self-hosted # This specifies to run on a self-hosted runner
    steps:
      - uses: actions/checkout@v2
      - name: Run keep-alive script
        run: bash /home/azureuser/keep-alive.sh
      - name: Restart runner if keep-alive fails
        if: failure()
        run: |
          cd /home/azureuser/actions-runner/
          nohup ./run.sh &
          sleep 30
          bash /home/azureuser/keep-alive.sh